# Generated by Django 3.2.3 on 2021-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
